name: main
# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.10'
          - '3.11'
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      # Initialize submodules
      - name: Git Submodule Update
        run: |
          git submodule init
          git submodule update
      # Create environment
      - name: create build environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: policy_uncertainty
          create-args: |
            python=${{ matrix.python-version }}
          init-shell: >-
            bash
            powershell
          cache-environment: true
      - name: run pytest
        shell: bash -el {0}
        run: |
          micromamba activate policy_uncertainty
          cd src
          pytest --cov-report=xml --cov=./
